/**
 * ui/block_kit_builder.ts
 *
 * Builds Slack Block Kit payloads for BurnoutRadar alert dashboards and
 * supporting messages. All blocks are typed as plain objects compatible with
 * the Slack Block Kit specification.
 *
 * Reference: https://api.slack.com/reference/block-kit/blocks
 */

import type { RiskProfile, Severity } from "../functions/evaluate_metrics.ts";

// ---------------------------------------------------------------------------
// Block Kit type aliases (minimal — only what BurnoutRadar uses)
// ---------------------------------------------------------------------------

/** A generic Slack Block Kit block object. */
export type Block = Record<string, unknown>;

// ---------------------------------------------------------------------------
// Risk profile display metadata
// ---------------------------------------------------------------------------

/** Human-readable label for each risk profile. */
const RISK_LABELS: Record<RiskProfile, string> = {
  key_person_dependency: "Key Person Dependency Risk",
  systemic_crunch_time: "Systemic Crunch Time Risk",
  silent_isolation: "Silent Isolation Risk",
  none: "Healthy Patterns",
};

/** Emoji prefix based on severity — guides the manager's urgency instinct. */
function severityEmoji(severity: Severity): string {
  switch (severity) {
    case "severe":
      return "🚨";
    case "moderate":
      return "⚠️";
    default:
      return "✅";
  }
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * buildAlertDashboard
 *
 * Constructs the full Slack Block Kit payload for a burnout alert.
 * Returned blocks should be passed directly to `chat.postMessage` as the
 * `blocks` field.
 *
 * Layout:
 *   1. Header block   – App name + channel + date
 *   2. Section block  – Severity emoji, risk type label, LLM summary
 *   3. Divider
 *   4. Section block  – Suggested action
 *   5. Context block  – Date + privacy notice
 *   6. Actions block  – Context-appropriate action buttons
 *
 * @param channelName     - Display name of the analysed channel (without #)
 * @param date            - ISO-8601 analysis date string
 * @param riskProfile     - Detected burnout risk profile
 * @param severity        - Alert severity level
 * @param llmSummary      - Plain-text summary generated by Claude
 * @param suggestedAction - Plain-text next-step suggestion from Claude
 * @returns               - Array of Block Kit block objects
 */
export function buildAlertDashboard(
  channelName: string,
  date: string,
  riskProfile: RiskProfile,
  severity: Severity,
  llmSummary: string,
  suggestedAction: string,
): Block[] {
  const emoji = severityEmoji(severity);
  const riskLabel = RISK_LABELS[riskProfile];
  const formattedDate = formatDate(date);

  const blocks: Block[] = [
    // ── 1. Header ───────────────────────────────────────────────────────────
    {
      type: "header",
      text: {
        type: "plain_text",
        text: `BurnoutRadar Alert: #${channelName}`,
        emoji: true,
      },
    },

    // ── 2. Risk summary section ──────────────────────────────────────────────
    {
      type: "section",
      text: {
        type: "mrkdwn",
        text:
          `${emoji} *${riskLabel}*\n\n${llmSummary}`,
      },
    },

    // ── 3. Divider ───────────────────────────────────────────────────────────
    { type: "divider" },

    // ── 4. Suggested action ──────────────────────────────────────────────────
    {
      type: "section",
      text: {
        type: "mrkdwn",
        text: `*💡 Suggested Next Step*\n${suggestedAction}`,
      },
    },

    // ── 5. Context / privacy notice ──────────────────────────────────────────
    {
      type: "context",
      elements: [
        {
          type: "mrkdwn",
          text: `📅 Analysis date: *${formattedDate}*  |  📊 Based on anonymised aggregate patterns. No individual data was accessed.`,
        },
      ],
    },

    // ── 6. Action buttons (context-dependent) ────────────────────────────────
    ...buildActionButtons(riskProfile),
  ];

  return blocks;
}

/**
 * buildNoBurnoutMessage
 *
 * Returns a lightweight Block Kit payload used when no risk is detected.
 * Provides positive reinforcement and maintains a regular check-in cadence.
 *
 * @param channelName - Display name of the analysed channel (without #)
 * @param date        - ISO-8601 analysis date string
 * @returns           - Array of Block Kit block objects
 */
export function buildNoBurnoutMessage(
  channelName: string,
  date: string,
): Block[] {
  const formattedDate = formatDate(date);

  return [
    {
      type: "header",
      text: {
        type: "plain_text",
        text: `BurnoutRadar Check-in: #${channelName}`,
        emoji: true,
      },
    },
    {
      type: "section",
      text: {
        type: "mrkdwn",
        text:
          "✅ *All healthy!*\n\nCommunication patterns in this channel are within normal, healthy ranges. Keep up the great work! 🎉",
      },
    },
    {
      type: "context",
      elements: [
        {
          type: "mrkdwn",
          text: `📅 Analysis date: *${formattedDate}*  |  📊 Based on anonymised aggregate patterns. No individual data was accessed.`,
        },
      ],
    },
  ];
}

// ---------------------------------------------------------------------------
// Private helpers
// ---------------------------------------------------------------------------

/**
 * buildActionButtons
 *
 * Returns an Actions block with buttons appropriate to the detected risk profile.
 * Each button maps to an action_id that is handled in action_handlers.ts.
 *
 * Button strategy:
 *  - key_person_dependency  → Review Workload Allocation (primary)
 *  - systemic_crunch_time   → Send Pulse Survey + Draft Comp Time Reminder
 *  - silent_isolation       → Suggest No-Meeting Day (primary)
 *  - none                   → No buttons (empty array)
 */
function buildActionButtons(riskProfile: RiskProfile): Block[] {
  if (riskProfile === "none") {
    return [];
  }

  let elements: Block[] = [];

  switch (riskProfile) {
    case "key_person_dependency":
      elements = [
        {
          type: "button",
          text: { type: "plain_text", text: "Review Workload Allocation", emoji: true },
          style: "primary",
          action_id: "trigger_workload_review",
          value: "workload_review",
        },
      ];
      break;

    case "systemic_crunch_time":
      elements = [
        {
          type: "button",
          text: { type: "plain_text", text: "Send Anonymous Pulse Survey", emoji: true },
          action_id: "trigger_pulse_survey",
          value: "pulse_survey",
        },
        {
          type: "button",
          text: { type: "plain_text", text: "Draft Comp Time Reminder", emoji: true },
          action_id: "draft_comp_time",
          value: "comp_time",
        },
      ];
      break;

    case "silent_isolation":
      elements = [
        {
          type: "button",
          text: { type: "plain_text", text: "Suggest No-Meeting Day", emoji: true },
          style: "primary",
          action_id: "suggest_no_meeting",
          value: "no_meeting_day",
        },
      ];
      break;
  }

  return [
    {
      type: "actions",
      elements,
    },
  ];
}

/**
 * formatDate
 *
 * Converts an ISO-8601 date string (YYYY-MM-DD) to a friendlier display
 * format (e.g. "Monday, July 7, 2025"). Falls back to the raw string if
 * parsing fails.
 */
function formatDate(isoDate: string): string {
  try {
    return new Date(isoDate).toLocaleDateString("en-US", {
      weekday: "long",
      year: "numeric",
      month: "long",
      day: "numeric",
    });
  } catch {
    return isoDate;
  }
}
